services:
  - type: web
    name: fenix-academy-frontend
    env: node
    plan: starter
    buildCommand: |
      npm install
      npm run build:render
    startCommand: |
      npx serve out -s
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_URL
        value: https://fenix-academy-frontend.onrender.com
      - key: NEXT_PUBLIC_APP_NAME
        value: Fênix Dev Academy
    healthCheckPath: /
    autoDeploy: true
    branch: main