version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: fenix_test
      POSTGRES_USER: fenix_test
      POSTGRES_PASSWORD: fenix_test
    ports:
      - "5434:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_test_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: python manage.py test --verbosity=2
    environment:
      - DJANGO_SETTINGS_MODULE=fenix_academy.settings.test
      - POSTGRES_DB=fenix_test
      - POSTGRES_USER=fenix_test
      - POSTGRES_PASSWORD=fenix_test
      - POSTGRES_HOST=db
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run test
    environment:
      - NODE_ENV=test
    volumes:
      - ./frontend:/app
      - /app/node_modules

  integration-tests:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: python manage.py test api.tests.test_integration --verbosity=2
    environment:
      - DJANGO_SETTINGS_MODULE=fenix_academy.settings.test
      - POSTGRES_DB=fenix_test
      - POSTGRES_USER=fenix_test
      - POSTGRES_PASSWORD=fenix_test
      - POSTGRES_HOST=db
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis
      - backend
    volumes:
      - ./backend:/app

volumes:
  postgres_test_data:
  redis_test_data: 