# Generated by Django 5.2.4 on 2025-07-28 23:08

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('title_pt', models.CharField(blank=True, help_text='Portuguese title', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('description_pt', models.TextField(blank=True, help_text='Portuguese description')),
                ('completion_date', models.DateTimeField(auto_now_add=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_hours', models.IntegerField(default=0, help_text='Total study hours')),
                ('certificate_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('issued_by', models.CharField(default='Fênix Dev Academy', max_length=200)),
                ('issued_by_pt', models.CharField(default='Fênix Dev Academy', help_text='Portuguese issuer name', max_length=200)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdfs/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='certificates/qr_codes/')),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='certificates/images/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('issued', 'Issued'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_url', models.URLField(blank=True)),
                ('template_used', models.CharField(default='default', max_length=100)),
                ('language', models.CharField(choices=[('en', 'English'), ('pt', 'Português')], default='en', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'certificate',
                'verbose_name_plural': 'certificates',
                'db_table': 'certificates',
            },
        ),
        migrations.CreateModel(
            name='CertificateAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('completion', 'Course Completion'), ('excellence', 'Academic Excellence'), ('speed', 'Fast Completion'), ('participation', 'High Participation'), ('helping', 'Helping Others'), ('innovation', 'Innovation'), ('leadership', 'Leadership'), ('persistence', 'Persistence')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('title_pt', models.CharField(blank=True, help_text='Portuguese title', max_length=200)),
                ('description', models.TextField()),
                ('description_pt', models.TextField(blank=True, help_text='Portuguese description')),
                ('criteria_met', models.JSONField(default=dict, help_text='Criteria that were met')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=50)),
                ('color', models.CharField(default='#FFD700', help_text='Achievement color', max_length=7)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'certificate achievement',
                'verbose_name_plural': 'certificate achievements',
                'db_table': 'certificate_achievements',
            },
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_pt', models.CharField(blank=True, help_text='Portuguese name', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('description_pt', models.TextField(blank=True, help_text='Portuguese description')),
                ('html_template', models.TextField(help_text='HTML template for certificate')),
                ('css_styles', models.TextField(help_text='CSS styles for certificate')),
                ('width', models.IntegerField(default=1200, help_text='Certificate width in pixels')),
                ('height', models.IntegerField(default=800, help_text='Certificate height in pixels')),
                ('background_color', models.CharField(default='#FFFFFF', help_text='Background color', max_length=7)),
                ('text_color', models.CharField(default='#000000', help_text='Text color', max_length=7)),
                ('logo_url', models.URLField(blank=True)),
                ('logo_position', models.CharField(choices=[('top-left', 'Top Left'), ('top-center', 'Top Center'), ('top-right', 'Top Right'), ('center-left', 'Center Left'), ('center', 'Center'), ('center-right', 'Center Right'), ('bottom-left', 'Bottom Left'), ('bottom-center', 'Bottom Center'), ('bottom-right', 'Bottom Right')], default='top-center', max_length=20)),
                ('title_font', models.CharField(default='Arial, sans-serif', max_length=100)),
                ('body_font', models.CharField(default='Arial, sans-serif', max_length=100)),
                ('title_font_size', models.IntegerField(default=48)),
                ('body_font_size', models.IntegerField(default=16)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('pt', 'Português')], default='en', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'certificate template',
                'verbose_name_plural': 'certificate templates',
                'db_table': 'certificate_templates',
            },
        ),
        migrations.CreateModel(
            name='CertificateVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('verification_method', models.CharField(choices=[('qr_code', 'QR Code'), ('url', 'Direct URL'), ('api', 'API'), ('admin', 'Admin Panel')], default='url', max_length=20)),
                ('is_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'certificate verification',
                'verbose_name_plural': 'certificate verifications',
                'db_table': 'certificate_verifications',
            },
        ),
    ]
