# Generated by Django 5.2.4 on 2025-07-28 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificateachievement',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='certificates.certificate'),
        ),
        migrations.AddField(
            model_name='certificateverification',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='certificates.certificate'),
        ),
        migrations.AddField(
            model_name='certificateverification',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_id'], name='certificate_certifi_a0a669_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['user', 'status'], name='certificate_user_id_4171b6_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['course', 'status'], name='certificate_course__9a6b69_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['completion_date'], name='certificate_complet_113420_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_number'], name='certificate_certifi_1d3ba1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('user', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='certificateachievement',
            unique_together={('certificate', 'achievement_type')},
        ),
        migrations.AddIndex(
            model_name='certificateverification',
            index=models.Index(fields=['certificate', 'verified_at'], name='certificate_certifi_fce4c7_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateverification',
            index=models.Index(fields=['verified_at'], name='certificate_verifie_749ae0_idx'),
        ),
    ]
