# Generated by Django 5.2.4 on 2025-07-28 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cohortanalysis',
            index=models.Index(fields=['cohort_date'], name='cohort_anal_cohort__cf143d_idx'),
        ),
        migrations.AddIndex(
            model_name='learninganalytics',
            index=models.Index(fields=['date'], name='learning_an_date_5d8ec9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='learninganalytics',
            unique_together={('date',)},
        ),
        migrations.AddIndex(
            model_name='performancemetrics',
            index=models.Index(fields=['metric_name', 'timestamp'], name='performance_metric__2bab3d_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetrics',
            index=models.Index(fields=['service', 'timestamp'], name='performance_service_2cb936_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuemetrics',
            index=models.Index(fields=['date'], name='revenue_met_date_fbe5df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='revenuemetrics',
            unique_together={('date',)},
        ),
        migrations.AddField(
            model_name='userjourney',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_type'], name='analytics_e_event_t_7fd62a_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['user', 'timestamp'], name='analytics_e_user_id_4d513c_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['session_id'], name='analytics_e_session_b3cbf5_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['timestamp'], name='analytics_e_timesta_47536d_idx'),
        ),
        migrations.AddIndex(
            model_name='userjourney',
            index=models.Index(fields=['user', 'start_time'], name='user_journe_user_id_4d3583_idx'),
        ),
        migrations.AddIndex(
            model_name='userjourney',
            index=models.Index(fields=['session_id'], name='user_journe_session_d6bc65_idx'),
        ),
    ]
