# Generated by Django 5.2.4 on 2025-07-28 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0002_initial'),
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skillgap',
            name='recommended_courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
        migrations.AddField(
            model_name='skillgap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlearningpath',
            name='completed_courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
        migrations.AddField(
            model_name='userlearningpath',
            name='learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_paths', to='recommendations.learningpath'),
        ),
        migrations.AddField(
            model_name='userlearningpath',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_learning_paths', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='learningpathcourse',
            unique_together={('learning_path', 'course')},
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['path_type'], name='learning_pa_path_ty_593592_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['difficulty'], name='learning_pa_difficu_7440e0_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['is_active'], name='learning_pa_is_acti_c7023b_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['is_featured'], name='learning_pa_is_feat_5bbd73_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', 'recommendation_type'], name='recommendat_user_id_373e78_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['algorithm'], name='recommendat_algorit_9f33ec_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['score'], name='recommendat_score_11d775_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['created_at'], name='recommendat_created_02802f_idx'),
        ),
        migrations.AddIndex(
            model_name='skillgap',
            index=models.Index(fields=['user', 'priority'], name='skill_gaps_user_id_f0b699_idx'),
        ),
        migrations.AddIndex(
            model_name='skillgap',
            index=models.Index(fields=['skill_category'], name='skill_gaps_skill_c_0cb008_idx'),
        ),
        migrations.AddIndex(
            model_name='skillgap',
            index=models.Index(fields=['gap_score'], name='skill_gaps_gap_sco_7b24cd_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehavior',
            index=models.Index(fields=['user', 'behavior_type'], name='user_behavi_user_id_5b4a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehavior',
            index=models.Index(fields=['content_type', 'object_id'], name='user_behavi_content_fe8dff_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehavior',
            index=models.Index(fields=['timestamp'], name='user_behavi_timesta_f7c28a_idx'),
        ),
        migrations.AddIndex(
            model_name='userlearningpath',
            index=models.Index(fields=['user', 'status'], name='user_learni_user_id_452dc7_idx'),
        ),
        migrations.AddIndex(
            model_name='userlearningpath',
            index=models.Index(fields=['learning_path', 'status'], name='user_learni_learnin_b33d03_idx'),
        ),
        migrations.AddIndex(
            model_name='userlearningpath',
            index=models.Index(fields=['progress_percentage'], name='user_learni_progres_82fa2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userlearningpath',
            unique_together={('user', 'learning_path')},
        ),
    ]
