# Generated by Django 5.2.4 on 2025-07-28 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exerciseprogress',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.exercise'),
        ),
        migrations.AddField(
            model_name='exerciseprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studysession',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='courses.course'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='courseprogress',
            index=models.Index(fields=['user', 'is_active'], name='course_prog_user_id_895a85_idx'),
        ),
        migrations.AddIndex(
            model_name='courseprogress',
            index=models.Index(fields=['course', 'is_completed'], name='course_prog_course__75b08c_idx'),
        ),
        migrations.AddIndex(
            model_name='courseprogress',
            index=models.Index(fields=['progress_percentage'], name='course_prog_progres_7b0c25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseprogress',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='exerciseprogress',
            index=models.Index(fields=['user', 'status'], name='exercise_pr_user_id_6b475a_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseprogress',
            index=models.Index(fields=['exercise', 'status'], name='exercise_pr_exercis_4f2d6f_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseprogress',
            index=models.Index(fields=['best_score'], name='exercise_pr_best_sc_5f8d71_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exerciseprogress',
            unique_together={('user', 'exercise')},
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['user', 'is_completed'], name='lesson_prog_user_id_247085_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['lesson', 'is_completed'], name='lesson_prog_lesson__7f1273_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['last_accessed'], name='lesson_prog_last_ac_53e15a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('user', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'start_time'], name='study_sessi_user_id_1acbae_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['course', 'session_type'], name='study_sessi_course__135431_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['duration_minutes'], name='study_sessi_duratio_ca90f2_idx'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['user', 'achievement_type'], name='user_achiev_user_id_7afe39_idx'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['difficulty'], name='user_achiev_difficu_6e2637_idx'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['awarded_at'], name='user_achiev_awarded_9c6d31_idx'),
        ),
    ]
