# Generated by Django 5.2.4 on 2025-07-28 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_pt', models.CharField(blank=True, help_text='Portuguese name', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('description_pt', models.TextField(blank=True, help_text='Portuguese description')),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_pt', models.CharField(blank=True, help_text='Portuguese title', max_length=200)),
                ('description', models.TextField()),
                ('description_pt', models.TextField(blank=True, help_text='Portuguese description')),
                ('exercise_type', models.CharField(choices=[('coding', 'Coding Challenge'), ('multiple_choice', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank'), ('true_false', 'True/False'), ('matching', 'Matching')], default='coding', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], default='easy', max_length=20)),
                ('instructions', models.TextField()),
                ('instructions_pt', models.TextField(blank=True, help_text='Portuguese instructions')),
                ('starter_code', models.TextField(blank=True)),
                ('solution_code', models.TextField(blank=True)),
                ('test_cases', models.JSONField(blank=True, default=list)),
                ('points', models.IntegerField(default=10)),
                ('max_attempts', models.IntegerField(default=3)),
                ('time_limit', models.IntegerField(default=0, help_text='Time limit in minutes (0 = no limit)')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'exercise',
                'verbose_name_plural': 'exercises',
                'db_table': 'exercises',
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_pt', models.CharField(blank=True, help_text='Portuguese title', max_length=200)),
                ('content', models.TextField(blank=True)),
                ('content_pt', models.TextField(blank=True, help_text='Portuguese content')),
                ('lesson_type', models.CharField(choices=[('video', 'Video Lesson'), ('text', 'Text Lesson'), ('quiz', 'Quiz'), ('exercise', 'Exercise'), ('project', 'Project')], default='video', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('video_url', models.URLField(blank=True)),
                ('video_duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('quiz_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
                'db_table': 'lessons',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_pt', models.CharField(blank=True, help_text='Portuguese title', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('description_pt', models.TextField(blank=True, help_text='Portuguese description')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
                'db_table': 'modules',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_pt', models.CharField(blank=True, help_text='Portuguese title', max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('description_pt', models.TextField(blank=True, help_text='Portuguese description')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/')),
                ('video_intro', models.URLField(blank=True, help_text='Introduction video URL')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_free', models.BooleanField(default=True)),
                ('duration_hours', models.IntegerField(default=0)),
                ('total_lessons', models.IntegerField(default=0)),
                ('total_exercises', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.category')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
    ]
