# Generated by Django 5.2.4 on 2025-07-28 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='streak',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='gamification.achievement'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_challenges', to='gamification.challenge'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['leaderboard', 'rank'], name='leaderboard_leaderb_bb9735_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['user', 'score'], name='leaderboard_user_id_0bf240_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leaderboardentry',
            unique_together={('leaderboard', 'user')},
        ),
        migrations.AddIndex(
            model_name='streak',
            index=models.Index(fields=['user', 'streak_type'], name='streaks_user_id_9d38b8_idx'),
        ),
        migrations.AddIndex(
            model_name='streak',
            index=models.Index(fields=['current_streak'], name='streaks_current_5e1c43_idx'),
        ),
        migrations.AddIndex(
            model_name='streak',
            index=models.Index(fields=['last_activity_date'], name='streaks_last_ac_61c647_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='streak',
            unique_together={('user', 'streak_type')},
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['user', 'is_completed'], name='user_achiev_user_id_171932_idx'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['achievement', 'is_completed'], name='user_achiev_achieve_d00f86_idx'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['completed_at'], name='user_achiev_complet_8c78fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
        migrations.AddIndex(
            model_name='userchallenge',
            index=models.Index(fields=['user', 'status'], name='user_challe_user_id_ecb192_idx'),
        ),
        migrations.AddIndex(
            model_name='userchallenge',
            index=models.Index(fields=['challenge', 'status'], name='user_challe_challen_e77d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='userchallenge',
            index=models.Index(fields=['joined_at'], name='user_challe_joined__2da768_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userchallenge',
            unique_together={('user', 'challenge')},
        ),
    ]
