// Route constants and utilities
export const ROUTES = {
    HOME: '/',
    LOGIN: '/auth/login',
    REGISTER: '/register',
    PROFILE: '/profile',
    COURSES: '/courses',
    COURSE: (slug: string) => `/course/${slug}`,
    COURSE_PURCHASE: (slug: string) => `/course/${slug}/purchase`,
    DASHBOARD: '/dashboard',
    HELP: '/help',
    CERTIFICATES: '/certificates',
    IDE: '/ide',
    IDE_ADVANCED: '/ide-advanced',
    IDE_ADVANCED_SIMPLE: '/ide-advanced-simple',
    FENIX_IDE: '/fenix-ide',
    INTELLISENSE: '/intellisense',
    SETTINGS: '/settings',
    CEO_DASHBOARD: '/ceo-dashboard',
    ADMIN: '/admin',
    ABOUT: '/about',
    PRICING: '/pricing',
    CONTACT: '/contact',
    BLOG: '/blog',
    CAREERS: '/careers',
    SUPPORT: '/support',
    COMMUNITY: '/community',
    FOUNDERS: '/founders',
    MY_COURSES: '/my-courses',
    PROGRESS: '/progress',
    EXPANDED_COURSES: '/expanded-courses',
    EXPANDED_DASHBOARD: '/expanded-dashboard',
    EXPANDED_SEARCH: '/expanded-search',
    EXPANDED_EXERCISES: '/expanded-exercises',
    EXPANDED_QUIZZES: '/expanded-quizzes',
    PAYMENT: '/payment',
    PAYMENTS: '/payments',
    SUBSCRIPTIONS: '/subscriptions',
    COMEÇAR_AGORA: '/auth/register',
    BECOME_STUDENT: '/become-student',
    LAUNCH: '/launch',
    AI: '/ai',
    ASSINATURAS: '/assinaturas',
    FATURAMENTO: '/faturamento',
    GESTAO_TRAFEGO: '/gestao-trafego',
    COURSES_CONTENT: '/courses-content',
    EXERCICIOS: '/exercicios',
    TERMS: '/terms',
    PRIVACY: '/privacy',
    COURSE_DETAIL: (slug: string) => `/course-detail/${slug}`,
    EXPANDED_COURSE_DETAIL: (slug: string) => `/expanded-course-detail/${slug}`,
} as const;

export const API_ROUTES = {
    AUTH: {
        LOGIN: '/api/auth/login',
        REGISTER: '/api/auth/register',
        LOGOUT: '/api/auth/logout',
        PROFILE: '/api/users/profile',
    },
    COURSES: {
        LIST: '/api/courses',
        DETAIL: (slug: string) => `/api/courses/${slug}`,
        PURCHASE: (slug: string) => `/api/courses/${slug}/purchase`,
    },
    PAYMENTS: {
        CREATE_INTENT: '/api/payments/create-intent',
        WEBHOOK: '/api/payments/webhook',
    },
} as const;

export type RouteKey = keyof typeof ROUTES;
export type ApiRouteKey = keyof typeof API_ROUTES;
