import { NextResponse } from 'next/server';

export async function GET() {
    try {
        const courses = [
            {
                id: 1,
                title: "Fundamentos de Desenvolvimento Web",
                description: "HTML, CSS, JavaScript e conceitos fundamentais para iniciantes.",
                instructor: "Prof. João Santos",
                level: "beginner",
                duration: "30 horas",
                students: 3456,
                rating: 4.7,
                price: 197,
                originalPrice: 297,
                image: "/courses/web-fundamentals.jpg",
                category: "Frontend",
                lessons: 28,
                certificate: true,
                discount: 34,
                featured: true,
                new: false
            },
            {
                id: 2,
                title: "React JS Avançado",
                description: "Hooks avançados, performance, testes e arquitetura de aplicações React.",
                instructor: "Lucas Oliveira",
                level: "advanced",
                duration: "40 horas",
                students: 2341,
                rating: 4.9,
                price: 447,
                originalPrice: 547,
                image: "/courses/react-advanced.jpg",
                category: "Frontend",
                lessons: 35,
                certificate: true,
                discount: 18,
                featured: true,
                new: true
            },
            {
                id: 3,
                title: "Node.js APIs REST",
                description: "Desenvolva APIs robustas e escaláveis com Node.js e Express.",
                instructor: "Carlos Mendes",
                level: "intermediate",
                duration: "35 horas",
                students: 892,
                rating: 4.9,
                price: 297,
                originalPrice: 397,
                image: "/courses/nodejs.jpg",
                category: "Backend",
                lessons: 32,
                certificate: true,
                discount: 25,
                featured: false,
                new: false
            },
            {
                id: 4,
                title: "Python Data Science",
                description: "Análise de dados, machine learning e visualização com Python.",
                instructor: "Dr. Ana Rodrigues",
                level: "intermediate",
                duration: "45 horas",
                students: 1567,
                rating: 4.8,
                price: 397,
                originalPrice: 497,
                image: "/courses/python-data.jpg",
                category: "Data Science",
                lessons: 38,
                certificate: true,
                discount: 20,
                featured: true,
                new: false
            },
            {
                id: 5,
                title: "DevOps e CI/CD",
                description: "Automatize deploy, monitoramento e infraestrutura como código.",
                instructor: "Roberto Silva",
                level: "advanced",
                duration: "50 horas",
                students: 445,
                rating: 4.8,
                price: 347,
                originalPrice: 447,
                image: "/courses/devops.jpg",
                category: "DevOps",
                lessons: 40,
                certificate: true,
                discount: 22,
                featured: false,
                new: true
            },
            {
                id: 6,
                title: "Flutter Mobile",
                description: "Desenvolva aplicativos móveis multiplataforma com Flutter.",
                instructor: "Fernanda Costa",
                level: "intermediate",
                duration: "42 horas",
                students: 1234,
                rating: 4.7,
                price: 347,
                originalPrice: 447,
                image: "/courses/flutter.jpg",
                category: "Mobile",
                lessons: 36,
                certificate: true,
                discount: 22,
                featured: false,
                new: false
            },
            {
                id: 7,
                title: "React Native Mobile",
                description: "Crie aplicativos nativos com React Native e JavaScript.",
                instructor: "Marcos Lima",
                level: "intermediate",
                duration: "38 horas",
                students: 987,
                rating: 4.6,
                price: 297,
                originalPrice: 397,
                image: "/courses/react-native.jpg",
                category: "Mobile",
                lessons: 32,
                certificate: true,
                discount: 25,
                featured: false,
                new: false
            },
            {
                id: 8,
                title: "AWS Cloud",
                description: "Infraestrutura na nuvem e serviços AWS para desenvolvedores.",
                instructor: "Alexandre Santos",
                level: "advanced",
                duration: "48 horas",
                students: 678,
                rating: 4.8,
                price: 397,
                originalPrice: 497,
                image: "/courses/aws.jpg",
                category: "Cloud",
                lessons: 40,
                certificate: true,
                discount: 20,
                featured: false,
                new: true
            },
            {
                id: 9,
                title: "Blockchain e Smart Contracts",
                description: "Desenvolvimento de aplicações descentralizadas e contratos inteligentes.",
                instructor: "Ricardo Oliveira",
                level: "advanced",
                duration: "45 horas",
                students: 456,
                rating: 4.7,
                price: 447,
                originalPrice: 547,
                image: "/courses/blockchain.jpg",
                category: "Blockchain",
                lessons: 38,
                certificate: true,
                discount: 18,
                featured: false,
                new: true
            },
            {
                id: 10,
                title: "Cibersegurança",
                description: "Proteção de sistemas, redes e dados contra ameaças digitais.",
                instructor: "Dra. Patricia Silva",
                level: "intermediate",
                duration: "52 horas",
                students: 789,
                rating: 4.9,
                price: 497,
                originalPrice: 597,
                image: "/courses/cybersecurity.jpg",
                category: "Security",
                lessons: 44,
                certificate: true,
                discount: 17,
                featured: true,
                new: false
            }
        ];

        return NextResponse.json({
            success: true,
            data: courses,
            total: courses.length
        });
    } catch (error) {
        return NextResponse.json(
            {
                success: false,
                error: 'Erro ao carregar cursos'
            },
            { status: 500 }
        );
    }
} 